// <auto-generated />
using System;
using ChristmasJoy.App.DbRepositories.SqLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChristmasJoy.App.Migrations
{
    [DbContext(typeof(ChristmasDbContext))]
    partial class ChristmasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("ChristmasJoy.App.Models.SqLiteModels.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CommentDate");

                    b.Property<int>("CommentType");

                    b.Property<string>("Content");

                    b.Property<int>("FromUserId");

                    b.Property<bool>("IsAnonymous");

                    b.Property<int>("ToUserId");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ChristmasJoy.App.Models.SqLiteModels.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CommentId");

                    b.Property<int?>("CommentId1");

                    b.Property<int>("FromUserId");

                    b.HasKey("Id");

                    b.HasIndex("CommentId1");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("ChristmasJoy.App.Models.SqLiteModels.SecretSanta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ReceiverUserId");

                    b.Property<int?>("SantaUserId");

                    b.HasKey("Id");

                    b.ToTable("SecretSantas");
                });

            modelBuilder.Entity("ChristmasJoy.App.Models.SqLiteModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<int>("CustomId");

                    b.Property<string>("Email");

                    b.Property<string>("HashedPassword");

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("SecretSantaFor");

                    b.Property<int?>("SecretSantaForId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChristmasJoy.App.Models.SqLiteModels.WishListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Item");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("WishListItems");
                });

            modelBuilder.Entity("ChristmasJoy.App.Models.SqLiteModels.Like", b =>
                {
                    b.HasOne("ChristmasJoy.App.Models.SqLiteModels.Comment")
                        .WithMany("Likes")
                        .HasForeignKey("CommentId1");
                });
#pragma warning restore 612, 618
        }
    }
}
